package expedicionesapp.ui;

import expedicionesapp.dao.ExpedicionesDao;
import expedicionesapp.model.Miembros;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import expedicionesapp.dao.MiembrosDao;
import expedicionesapp.dao.Miembros_expedicionesDAO;
import expedicionesapp.model.Expediciones;
import expedicionesapp.model.Miembros_expediciones;
import java.awt.Dimension;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
public class MiembrosFrame extends javax.swing.JFrame {
            //lista de miembros
    private List<Miembros> muestra = new ArrayList();//Miembros que se muestran en la tabla
    private List<Miembros> listaMiembros = new ArrayList();//miebros de la que van a elazarse
    private List<Miembros> miembrosNuevos = new ArrayList();//Lista de miembros del cual es su primera expedicion
    
    private MiembrosDao mmbrsDAO = new MiembrosDao();
    private ExpedicionesDao expsDAO = new ExpedicionesDao();
    private Miembros_expedicionesDAO mmb_eDAO = new Miembros_expedicionesDAO();
    public MiembrosFrame() {
        initComponents();
        cargarTablaMiembros();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevaExpedicionBtn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nuevoMiembroBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MiembrosTable = new javax.swing.JTable();
        expedicionesProcesoLabel = new javax.swing.JLabel();
        picoIdLabel = new javax.swing.JLabel();
        accidenteIdLabel = new javax.swing.JLabel();
        altitudLabel = new javax.swing.JLabel();
        cuposLabel = new javax.swing.JLabel();
        mortalidadLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        resultadoLabel = new javax.swing.JLabel();
        motivoLabel = new javax.swing.JLabel();
        Nacionalidadtxt = new javax.swing.JTextField();
        ApellidoTxt = new javax.swing.JTextField();
        Nombretxt = new javax.swing.JTextField();
        SexoTxt = new javax.swing.JTextField();
        lidertxt = new javax.swing.JTextField();
        staftxt = new javax.swing.JTextField();
        Nacimientotxt = new javax.swing.JTextField();
        fallecidoTxt = new javax.swing.JTextField();
        expedicionesBtn = new javax.swing.JButton();
        borrarFormBtn = new javax.swing.JButton();
        borrarMiembroBtn = new javax.swing.JButton();
        buscarMiembroBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        nuevaExpedicionBtn1.setText("Nueva Expedicion");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(106, 146, 218));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nuevoMiembroBtn.setText("Nuevo miembro");
        nuevoMiembroBtn.setActionCommand("Nuevo Miembro");
        nuevoMiembroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMiembroBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nuevoMiembroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, 40));

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        jPanel1.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, 39));

        MiembrosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(MiembrosTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 545, 300));

        expedicionesProcesoLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        expedicionesProcesoLabel.setForeground(new java.awt.Color(0, 0, 0));
        expedicionesProcesoLabel.setText("Miembros De la expedicion");
        jPanel1.add(expedicionesProcesoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        picoIdLabel.setText("Nacionalidad");
        jPanel1.add(picoIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        accidenteIdLabel.setText("Nombre");
        jPanel1.add(accidenteIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 70, -1));

        altitudLabel.setText("Apellido:");
        jPanel1.add(altitudLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        cuposLabel.setText("Sexo");
        jPanel1.add(cuposLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        mortalidadLabel.setText("Es lider");
        jPanel1.add(mortalidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        fechaLabel.setText("Es staff");
        jPanel1.add(fechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        resultadoLabel.setText("Año nacimiento");
        jPanel1.add(resultadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        motivoLabel.setText("Fallecido");
        jPanel1.add(motivoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, -1, -1));

        Nacionalidadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NacionalidadtxtActionPerformed(evt);
            }
        });
        jPanel1.add(Nacionalidadtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 108, 27));

        ApellidoTxt.setMinimumSize(new java.awt.Dimension(120, 120));
        ApellidoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoTxtActionPerformed(evt);
            }
        });
        jPanel1.add(ApellidoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 108, 27));

        Nombretxt.setMinimumSize(new java.awt.Dimension(120, 120));
        Nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombretxtActionPerformed(evt);
            }
        });
        jPanel1.add(Nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 108, 27));

        SexoTxt.setMinimumSize(new java.awt.Dimension(120, 120));
        jPanel1.add(SexoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 108, 27));

        lidertxt.setMinimumSize(new java.awt.Dimension(120, 120));
        jPanel1.add(lidertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 110, 27));

        staftxt.setMinimumSize(new java.awt.Dimension(120, 120));
        jPanel1.add(staftxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 110, 27));

        Nacimientotxt.setMinimumSize(new java.awt.Dimension(120, 120));
        Nacimientotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NacimientotxtActionPerformed(evt);
            }
        });
        jPanel1.add(Nacimientotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 110, 27));

        fallecidoTxt.setMinimumSize(new java.awt.Dimension(120, 120));
        jPanel1.add(fallecidoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 110, 27));

        expedicionesBtn.setText("Expedicion");
        expedicionesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expedicionesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(expedicionesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, -1, 39));

        borrarFormBtn.setText("Limpiar Formulario");
        borrarFormBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarFormBtnMouseClicked(evt);
            }
        });
        borrarFormBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarFormBtnActionPerformed(evt);
            }
        });
        jPanel1.add(borrarFormBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 160, 39));

        borrarMiembroBtn.setText("Borrar miembro");
        borrarMiembroBtn.setMaximumSize(new java.awt.Dimension(121, 27));
        borrarMiembroBtn.setMinimumSize(new java.awt.Dimension(121, 27));
        borrarMiembroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarMiembroBtnActionPerformed(evt);
            }
        });
        jPanel1.add(borrarMiembroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, 40));

        buscarMiembroBtn.setText("Buscar miembros exp.");
        buscarMiembroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMiembroBtnActionPerformed(evt);
            }
        });
        jPanel1.add(buscarMiembroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, 39));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\54224\\Desktop\\images\\background.png")); // NOI18N
        background.setText("jLabel1");
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 854, 542));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarTablaMiembros() {
        // Define las columnas de la tabla
        String[] columnNames = {"Id","Nacionalidad","Nombre","Apellido","Sexo","lider","staff","nacimiento","Fallecido"};
        // Crea un DefaultTableModel. El segundo argumento es el número inicial de filas (0)
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);   
        // Itera sobre la lista y añade cada expedición como una fila a la tabla
        for (Miembros miembro : muestra) {
            Object[] rowData = new Object[9]; // 9 columnas
            rowData[0] = miembro.getId();
            rowData[1] = miembro.getNacionalidad();
            rowData[2] = miembro.getNombre();
            rowData[3] = miembro.getApellido();
            rowData[4] = miembro.getSexo();
            rowData[5] = miembro.getEs_lider();
            rowData[6] = miembro.getEs_staff();
            rowData[7] = miembro.getAno_nacimiento();
            rowData[8] = miembro.getFallecido();
            model.addRow(rowData);
        } 
        // Asigna el modelo al JTable
        MiembrosTable.setModel(model); 
    }//muestra la tablita de todos los miembros que se van a agregar
    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // Crea una instancia de ScreenFrame
        ExpedicionesFrame screenFrame = new ExpedicionesFrame();
        // Hace visible ScreenFrame
        screenFrame.setVisible(true);

        // Cierra la ventana actual
        this.dispose(); // 'this' se refiere al JFrame actual
    }//GEN-LAST:event_volverBtnActionPerformed
    private void agregarMiembro(){
            // Validar campos String
    String nacionalidad = Nacionalidadtxt.getText().trim();
    String nombre = Nombretxt.getText().trim();
    String apellido = ApellidoTxt.getText().trim();
    String sexo = SexoTxt.getText().trim();

    if (nacionalidad.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || sexo.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Todos los campos de texto deben estar completos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar campos enteros 0 o 1
    int esLider, esStaff, fallecido;
    try {
        esLider = Integer.parseInt(lidertxt.getText().trim());
        esStaff = Integer.parseInt(staftxt.getText().trim());
        fallecido = Integer.parseInt(fallecidoTxt.getText().trim());

        if ((esLider != 0 && esLider != 1) || (esStaff != 0 && esStaff != 1) || (fallecido != 0 && fallecido != 1)) {
            JOptionPane.showMessageDialog(null, "Los campos 'Líder', 'Staff' y 'Fallecido' deben ser 0 o 1.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Los campos 'es Líder', 'es Staff' y 'Fallecido' deben ser números enteros (0 o 1).", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar año de nacimiento (solo que sea un número válido)
    int anoNacimiento;
    try {
        String nacimientoStr = Nacimientotxt.getText().trim();
        if (nacimientoStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo 'Año de nacimiento' no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        anoNacimiento = Integer.parseInt(nacimientoStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El campo 'Año de nacimiento' debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Crear el objeto y agregarlo
    Miembros miembroN = new Miembros();
    miembroN.setNacionalidad(nacionalidad);
    miembroN.setNombre(nombre);
    miembroN.setApellido(apellido);
    miembroN.setSexo(sexo);
    miembroN.setEs_lider(esLider);
    miembroN.setEs_staff(esStaff);
    miembroN.setAno_nacimiento(anoNacimiento);
    miembroN.setFallecido(fallecido);

    
    try{
        int idc = mmbrsDAO.miembroYaExiste(miembroN);
        if(-1 != idc){//si el miembro existe devuelve el id que no puede ser -1. si no el codigo del DAO devuelve -1
           JOptionPane.showMessageDialog(null,"Este miembro ya a hecho expediciones");
           miembroN.setId(idc);//cambia la id que esta en la bd
           listaMiembros.add(miembroN);//añade a la lista de miembros el miembro existente
        }else{
           JOptionPane.showMessageDialog(null,"Miembro nuevo. Se aniadira a la Base de datos");
           miembrosNuevos.add(miembroN);//la añade a la lista que se va a agregar a miembros
        }
        muestra.add(miembroN);//agrega a la lista q se muestra
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, "Error al chequear base de datos" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);       
    }
    cargarTablaMiembros();
}//agrega miembro a su lista correspondiente
private synchronized void enlazarAExpedicion(){
        String input = JOptionPane.showInputDialog(null, "Ingrese el Id de la expedicion:");//Muestra el input

        if(input !=null && !input.trim().isEmpty()){
            try{
                int idExpedicion = Integer.parseInt(input.trim());
                Expediciones expedicion=expsDAO.getExpeditionById(idExpedicion);
                if(expedicion!=null){//si la expedicion existe
                    JOptionPane.showMessageDialog(null, "Expedicion seleccionada " + expedicion.getId()+ " Fecha "+ expedicion.getFecha());
                    for(Miembros miembroA:miembrosNuevos){
                        try{
                            if(mmbrsDAO.insertMember(miembroA)){//si el miembro nuevo se añade a la tabla de miembros
                                Miembros aux = mmbrsDAO.obtenerUltimoMiembro();
                                listaMiembros.add(aux);//Se añade a la lista de miembros que se va a enlazar a la expedicion
                                System.out.println("Id ultimo miembro: "+ aux.getId());
                            }
                        }catch(SQLException e){
                            JOptionPane.showMessageDialog(null, "Error al chequear base de datos al enlazar" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);   
                        }
                    }
                    Miembros_expediciones m_e = new Miembros_expediciones(expedicion, listaMiembros);  
                    //esto fue para testear 
                    /*System.out.println("Referi: "+m_e.getId_expediciones().getId()+" Miembros: ");
                    for(Miembros ver:m_e.getId_miembros()){
                        System.out.println("ID: "+ver.getId());
                    }*/
                    try{
                        mmb_eDAO.unirMiembrosExpediciones(m_e);
                    }catch(SQLException e){
                        JOptionPane.showMessageDialog(null, "Error al acceder a la base de datos" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);       
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"No se encontro la expedicion");
                }
            }catch(Exception e){throw e;}
        }else{
            JOptionPane.showMessageDialog(null, "Expedicion cancelada");
        }
        //reseteo de listas
      muestra = new ArrayList();
    listaMiembros = new ArrayList();
    miembrosNuevos = new ArrayList();
    cargarTablaMiembros();
    }//inserta miembros nuevos
    private Miembros obtenerMiembroListado(){
        int miembroS = MiembrosTable.getSelectedRow();
        if(miembroS == -1){
            JOptionPane.showMessageDialog(null, "Sleccione un miembro");
            return null;
        }
        return muestra.get(miembroS);
    }//Selecciona el miembro de la lista
    //botones y celdas de texto
    private void NacionalidadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NacionalidadtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NacionalidadtxtActionPerformed

    private void ApellidoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoTxtActionPerformed

    private void NombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombretxtActionPerformed
//Boton de  agregar miembros a expedicion
    private void expedicionesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expedicionesBtnActionPerformed
        enlazarAExpedicion();
    }//GEN-LAST:event_expedicionesBtnActionPerformed
//Boton que borra lo puesto en las celdas
    private void borrarFormBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarFormBtnActionPerformed
        Nacionalidadtxt.setText("");
        Nombretxt.setText("");
        ApellidoTxt.setText("");
        SexoTxt.setText("");
        lidertxt.setText("");
        staftxt.setText("");
        Nacimientotxt.setText("");
        fallecidoTxt.setText("");

    }//GEN-LAST:event_borrarFormBtnActionPerformed

    private void nuevoMiembroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMiembroBtnActionPerformed
        agregarMiembro();
    }//GEN-LAST:event_nuevoMiembroBtnActionPerformed

    private void NacimientotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NacimientotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NacimientotxtActionPerformed
    //Borra miembro de linea seleccionada
    private void borrarMiembroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarMiembroBtnActionPerformed
    Miembros miembro = obtenerMiembroListado();//Miembro seleccionado
    if (miembro == null) {// si no esta seleccionado no hace nada
        return; 
    }else{
    int confirmacion = JOptionPane.showConfirmDialog(null,
            "¿Estás seguro de que querés eliminar a " + miembro.getNombre() + " " + miembro.getApellido() + "?",
            "Confirmar eliminación", JOptionPane.YES_NO_OPTION);//Asegurar q va a eliminar bien
    if (confirmacion == JOptionPane.YES_OPTION) {
        muestra.remove(miembro); // elimina de la lista
        //if(miembro.getId()){}        // actualiza la JTable
        JOptionPane.showMessageDialog(null, "Miembro eliminado correctamente.");
        cargarTablaMiembros(); 
    }
    }
    }//GEN-LAST:event_borrarMiembroBtnActionPerformed

    private void buscarMiembroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMiembroBtnActionPerformed
        String input = JOptionPane.showInputDialog(this, "Ingrese el ID de la expedición:", "Buscar Miembros", JOptionPane.QUESTION_MESSAGE);
    if (input != null && !input.trim().isEmpty()) {
        try {
            int idExpedicion = Integer.parseInt(input.trim());

            List<Object[]> miembros = mmbrsDAO.obtenerMiembrosPorExpedicion(idExpedicion);

            if (miembros.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron miembros para la expedición ID " + idExpedicion, "Sin Resultados", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            String[] columnas = {"ID", "Nombre", "Apellido", "Nacionalidad", "Sexo", "Líder", "Staff", "Nacimiento", "Fallecido"};
            Object[][] datos = new Object[miembros.size()][columnas.length];

            for (int i = 0; i < miembros.size(); i++) {
                datos[i] = miembros.get(i);
            }

            JTable tabla = new JTable(datos, columnas);
            JScrollPane scrollPane = new JScrollPane(tabla);
            scrollPane.setPreferredSize(new Dimension(700, 300));

            JOptionPane.showMessageDialog(this, scrollPane, "Miembros de la Expedición " + idExpedicion, JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_buscarMiembroBtnActionPerformed

    private void borrarFormBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarFormBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarFormBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiembrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiembrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiembrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiembrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiembrosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoTxt;
    private javax.swing.JTable MiembrosTable;
    private javax.swing.JTextField Nacimientotxt;
    private javax.swing.JTextField Nacionalidadtxt;
    private javax.swing.JTextField Nombretxt;
    private javax.swing.JTextField SexoTxt;
    private javax.swing.JLabel accidenteIdLabel;
    private javax.swing.JLabel altitudLabel;
    private javax.swing.JLabel background;
    private javax.swing.JButton borrarFormBtn;
    private javax.swing.JButton borrarMiembroBtn;
    private javax.swing.JButton buscarMiembroBtn;
    private javax.swing.JLabel cuposLabel;
    private javax.swing.JButton expedicionesBtn;
    private javax.swing.JLabel expedicionesProcesoLabel;
    private javax.swing.JTextField fallecidoTxt;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lidertxt;
    private javax.swing.JLabel mortalidadLabel;
    private javax.swing.JLabel motivoLabel;
    private javax.swing.JButton nuevaExpedicionBtn1;
    private javax.swing.JButton nuevoMiembroBtn;
    private javax.swing.JLabel picoIdLabel;
    private javax.swing.JLabel resultadoLabel;
    private javax.swing.JTextField staftxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
