package expedicionesapp.ui;

import expedicionesapp.dao.ExpedicionesDao;
import expedicionesapp.model.Miembros;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import expedicionesapp.dao.MiembrosDao;
import expedicionesapp.dao.Miembros_expedicionesDAO;
import expedicionesapp.model.Expediciones;
import expedicionesapp.model.Miembros_expediciones;
import java.awt.Dimension;
import java.sql.SQLException;
import javax.swing.JScrollPane;
import javax.swing.JTable;
public class MiembrosFrame extends javax.swing.JFrame {
            //lista de miembros
    private List<Miembros> muestra = new ArrayList();//Miembros que se muestran en la tabla
    private List<Miembros> listaMiembros = new ArrayList();//miebros de la que van a elazarse
    private List<Miembros> miembrosNuevos = new ArrayList();//Lista de miembros del cual es su primera expedicion
    
    private MiembrosDao mmbrsDAO = new MiembrosDao();
    private ExpedicionesDao expsDAO = new ExpedicionesDao();
    private Miembros_expedicionesDAO mmb_eDAO = new Miembros_expedicionesDAO();
    public MiembrosFrame() {
        initComponents();
        cargarTablaMiembros();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevaExpedicionBtn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nuevoMiembro = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MiembrosTable = new javax.swing.JTable();
        expedicionesProcesoLabel = new javax.swing.JLabel();
        picoIdLabel = new javax.swing.JLabel();
        accidenteIdLabel = new javax.swing.JLabel();
        altitudLabel = new javax.swing.JLabel();
        cuposLabel = new javax.swing.JLabel();
        mortalidadLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        resultadoLabel = new javax.swing.JLabel();
        motivoLabel = new javax.swing.JLabel();
        Nacionalidadtxt = new javax.swing.JTextField();
        ApellidoTxt = new javax.swing.JTextField();
        Nombretxt = new javax.swing.JTextField();
        SexoTxt = new javax.swing.JTextField();
        lidertxt = new javax.swing.JTextField();
        staftxt = new javax.swing.JTextField();
        Nacimientotxt = new javax.swing.JTextField();
        fallecidoTxt = new javax.swing.JTextField();
        Miembros = new javax.swing.JButton();
        BorrarBtn1 = new javax.swing.JButton();
        BorrarMiembrobutton = new javax.swing.JButton();
        buscarMiembro = new javax.swing.JButton();

        nuevaExpedicionBtn1.setText("Nueva Expedicion");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuevoMiembro.setText("Nuevo miembro");
        nuevoMiembro.setActionCommand("Nuevo Miembro");
        nuevoMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMiembroActionPerformed(evt);
            }
        });

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        MiembrosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(MiembrosTable);

        expedicionesProcesoLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        expedicionesProcesoLabel.setText("Miembros De la expedicion");

        picoIdLabel.setText("Nacionalidad");

        accidenteIdLabel.setText("Nombre");

        altitudLabel.setText("Apellido:");

        cuposLabel.setText("Sexo");

        mortalidadLabel.setText("es lider");

        fechaLabel.setText("es staff");

        resultadoLabel.setText("año nacimiento");

        motivoLabel.setText("Fallecido");

        Nacionalidadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NacionalidadtxtActionPerformed(evt);
            }
        });

        ApellidoTxt.setMinimumSize(new java.awt.Dimension(120, 120));
        ApellidoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoTxtActionPerformed(evt);
            }
        });

        Nombretxt.setMinimumSize(new java.awt.Dimension(120, 120));
        Nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombretxtActionPerformed(evt);
            }
        });

        SexoTxt.setMinimumSize(new java.awt.Dimension(120, 120));

        lidertxt.setMinimumSize(new java.awt.Dimension(120, 120));

        staftxt.setMinimumSize(new java.awt.Dimension(120, 120));

        Nacimientotxt.setMinimumSize(new java.awt.Dimension(120, 120));
        Nacimientotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NacimientotxtActionPerformed(evt);
            }
        });

        fallecidoTxt.setMinimumSize(new java.awt.Dimension(120, 120));

        Miembros.setText("Expedicion");
        Miembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiembrosActionPerformed(evt);
            }
        });

        BorrarBtn1.setText("Borrar");
        BorrarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarBtn1ActionPerformed(evt);
            }
        });

        BorrarMiembrobutton.setText("Borrar miembro");
        BorrarMiembrobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarMiembrobuttonActionPerformed(evt);
            }
        });

        buscarMiembro.setText("Bucar miembros exp.");
        buscarMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMiembroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(expedicionesProcesoLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(nuevoMiembro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BorrarMiembrobutton)
                                    .addGap(41, 41, 41)
                                    .addComponent(volverBtn)
                                    .addGap(55, 55, 55)
                                    .addComponent(Miembros)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(buscarMiembro)))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(picoIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(altitudLabel)
                                        .addComponent(cuposLabel)
                                        .addComponent(mortalidadLabel)
                                        .addComponent(accidenteIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Nombretxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ApellidoTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SexoTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lidertxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Nacionalidadtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(resultadoLabel)
                                        .addComponent(motivoLabel)
                                        .addComponent(fechaLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Nacimientotxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fallecidoTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(staftxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(BorrarBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(expedicionesProcesoLabel)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(picoIdLabel)
                            .addComponent(Nacionalidadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accidenteIdLabel)
                            .addComponent(Nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ApellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SexoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cuposLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lidertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mortalidadLabel)))
                            .addComponent(altitudLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staftxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nacimientotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultadoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fallecidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(motivoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BorrarBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(volverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevoMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Miembros, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BorrarMiembrobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarTablaMiembros() {
        // Define las columnas de la tabla
        String[] columnNames = {"Id","Nacionalidad","Nombre","Apellido","Sexo","lider","staff","nacimiento","Fallecido"};
        // Crea un DefaultTableModel. El segundo argumento es el número inicial de filas (0)
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);   
        // Itera sobre la lista y añade cada expedición como una fila a la tabla
        for (Miembros miembro : muestra) {
            Object[] rowData = new Object[9]; // 9 columnas
            rowData[0] = miembro.getId();
            rowData[1] = miembro.getNacionalidad();
            rowData[2] = miembro.getNombre();
            rowData[3] = miembro.getApellido();
            rowData[4] = miembro.getSexo();
            rowData[5] = miembro.getEs_lider();
            rowData[6] = miembro.getEs_staff();
            rowData[7] = miembro.getAno_nacimiento();
            rowData[8] = miembro.getFallecido();
            model.addRow(rowData);
        } 
        // Asigna el modelo al JTable
        MiembrosTable.setModel(model); 
    }//muestra la tablita de todos los miembros que se van a agregar
    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // Crea una instancia de ScreenFrame
        ExpedicionesFrame screenFrame = new ExpedicionesFrame();
        // Hace visible ScreenFrame
        screenFrame.setVisible(true);

        // Cierra la ventana actual
        this.dispose(); // 'this' se refiere al JFrame actual
    }//GEN-LAST:event_volverBtnActionPerformed
    private void agregarMiembro(){
            // Validar campos String
    String nacionalidad = Nacionalidadtxt.getText().trim();
    String nombre = Nombretxt.getText().trim();
    String apellido = ApellidoTxt.getText().trim();
    String sexo = SexoTxt.getText().trim();

    if (nacionalidad.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || sexo.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Todos los campos de texto deben estar completos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar campos enteros 0 o 1
    int esLider, esStaff, fallecido;
    try {
        esLider = Integer.parseInt(lidertxt.getText().trim());
        esStaff = Integer.parseInt(staftxt.getText().trim());
        fallecido = Integer.parseInt(fallecidoTxt.getText().trim());

        if ((esLider != 0 && esLider != 1) || (esStaff != 0 && esStaff != 1) || (fallecido != 0 && fallecido != 1)) {
            JOptionPane.showMessageDialog(null, "Los campos 'Líder', 'Staff' y 'Fallecido' deben ser 0 o 1.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Los campos 'es Líder', 'es Staff' y 'Fallecido' deben ser números enteros (0 o 1).", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar año de nacimiento (solo que sea un número válido)
    int anoNacimiento;
    try {
        String nacimientoStr = Nacimientotxt.getText().trim();
        if (nacimientoStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo 'Año de nacimiento' no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        anoNacimiento = Integer.parseInt(nacimientoStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El campo 'Año de nacimiento' debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Crear el objeto y agregarlo
    Miembros miembroN = new Miembros();
    miembroN.setNacionalidad(nacionalidad);
    miembroN.setNombre(nombre);
    miembroN.setApellido(apellido);
    miembroN.setSexo(sexo);
    miembroN.setEs_lider(esLider);
    miembroN.setEs_staff(esStaff);
    miembroN.setAno_nacimiento(anoNacimiento);
    miembroN.setFallecido(fallecido);

    
    try{
        int idc = mmbrsDAO.miembroYaExiste(miembroN);
        if(-1 != idc){//si el miembro existe devuelve el id que no puede ser -1. si no el codigo del DAO devuelve -1
           JOptionPane.showMessageDialog(null,"Este miembro ya a hecho expediciones");
           miembroN.setId(idc);//cambia la id que esta en la bd
           listaMiembros.add(miembroN);//añade a la lista de miembros el miembro existente
        }else{
           JOptionPane.showMessageDialog(null,"Miembro nuevo. Se aniadira a la Base de datos");
           miembrosNuevos.add(miembroN);//la añade a la lista que se va a agregar a miembros
        }
        muestra.add(miembroN);//agrega a la lista q se muestra
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, "Error al chequear base de datos" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);       
    }
    cargarTablaMiembros();
}//agrega miembro a su lista correspondiente
private synchronized void enlazarAExpedicion(){
        String input = JOptionPane.showInputDialog(null, "Ingrese el Id de la expedicion:");//Muestra el input

        if(input !=null && !input.trim().isEmpty()){
            try{
                int idExpedicion = Integer.parseInt(input.trim());
                Expediciones expedicion=expsDAO.getExpeditionById(idExpedicion);
                if(expedicion!=null){//si la expedicion existe
                    JOptionPane.showMessageDialog(null, "Expedicion seleccionada " + expedicion.getId()+ " Fecha "+ expedicion.getFecha());
                    for(Miembros miembroA:miembrosNuevos){
                        try{
                            if(mmbrsDAO.insertMember(miembroA)){//si el miembro nuevo se añade a la tabla de miembros
                                Miembros aux = mmbrsDAO.obtenerUltimoMiembro();
                                listaMiembros.add(aux);//Se añade a la lista de miembros que se va a enlazar a la expedicion
                                System.out.println("Id ultimo miembro: "+ aux.getId());
                            }
                        }catch(SQLException e){
                            JOptionPane.showMessageDialog(null, "Error al chequear base de datos al enlazar" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);   
                        }
                    }
                    Miembros_expediciones m_e = new Miembros_expediciones(expedicion, listaMiembros);  
                    //esto fue para testear 
                    /*System.out.println("Referi: "+m_e.getId_expediciones().getId()+" Miembros: ");
                    for(Miembros ver:m_e.getId_miembros()){
                        System.out.println("ID: "+ver.getId());
                    }*/
                    try{
                        mmb_eDAO.unirMiembrosExpediciones(m_e);
                    }catch(SQLException e){
                        JOptionPane.showMessageDialog(null, "Error al acceder a la base de datos" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);       
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"No se encontro la expedicion");
                }
            }catch(Exception e){throw e;}
        }else{
            JOptionPane.showMessageDialog(null, "Expedicion cancelada");
        }
        //reseteo de listas
      muestra = new ArrayList();
    listaMiembros = new ArrayList();
    miembrosNuevos = new ArrayList();
    cargarTablaMiembros();
    }//inserta miembros nuevos
    private Miembros obtenerMiembroListado(){
        int miembroS = MiembrosTable.getSelectedRow();
        if(miembroS == -1){
            JOptionPane.showMessageDialog(null, "Sleccione un miembro");
            return null;
        }
        return muestra.get(miembroS);
    }//Selecciona el miembro de la lista
    //botones y celdas de texto
    private void NacionalidadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NacionalidadtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NacionalidadtxtActionPerformed

    private void ApellidoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoTxtActionPerformed

    private void NombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombretxtActionPerformed
//Boton de  agregar miembros a expedicion
    private void MiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiembrosActionPerformed
        enlazarAExpedicion();
    }//GEN-LAST:event_MiembrosActionPerformed
//Boton que borra lo puesto en las celdas
    private void BorrarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarBtn1ActionPerformed
        Nacionalidadtxt.setText("");
        Nombretxt.setText("");
        ApellidoTxt.setText("");
        SexoTxt.setText("");
        lidertxt.setText("");
        staftxt.setText("");
        Nacimientotxt.setText("");
        fallecidoTxt.setText("");

    }//GEN-LAST:event_BorrarBtn1ActionPerformed

    private void nuevoMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMiembroActionPerformed
        agregarMiembro();
    }//GEN-LAST:event_nuevoMiembroActionPerformed

    private void NacimientotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NacimientotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NacimientotxtActionPerformed
    //Borra miembro de linea seleccionada
    private void BorrarMiembrobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarMiembrobuttonActionPerformed
    Miembros miembro = obtenerMiembroListado();//Miembro seleccionado
    if (miembro == null) {// si no esta seleccionado no hace nada
        return; 
    }else{
    int confirmacion = JOptionPane.showConfirmDialog(null,
            "¿Estás seguro de que querés eliminar a " + miembro.getNombre() + " " + miembro.getApellido() + "?",
            "Confirmar eliminación", JOptionPane.YES_NO_OPTION);//Asegurar q va a eliminar bien
    if (confirmacion == JOptionPane.YES_OPTION) {
        muestra.remove(miembro); // elimina de la lista
        //if(miembro.getId()){}
        cargarTablaMiembros();         // actualiza la JTable
        JOptionPane.showMessageDialog(null, "Miembro eliminado correctamente.");
    }
    }
    }//GEN-LAST:event_BorrarMiembrobuttonActionPerformed

    private void buscarMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMiembroActionPerformed
        String input = JOptionPane.showInputDialog(this, "Ingrese el ID de la expedición:", "Buscar Miembros", JOptionPane.QUESTION_MESSAGE);
    if (input != null && !input.trim().isEmpty()) {
        try {
            int idExpedicion = Integer.parseInt(input.trim());

            List<Object[]> miembros = mmbrsDAO.obtenerMiembrosPorExpedicion(idExpedicion);

            if (miembros.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron miembros para la expedición ID " + idExpedicion, "Sin Resultados", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            String[] columnas = {"ID", "Nombre", "Apellido", "Nacionalidad", "Sexo", "Líder", "Staff", "Nacimiento", "Fallecido"};
            Object[][] datos = new Object[miembros.size()][columnas.length];

            for (int i = 0; i < miembros.size(); i++) {
                datos[i] = miembros.get(i);
            }

            JTable tabla = new JTable(datos, columnas);
            JScrollPane scrollPane = new JScrollPane(tabla);
            scrollPane.setPreferredSize(new Dimension(700, 300));

            JOptionPane.showMessageDialog(this, scrollPane, "Miembros de la Expedición " + idExpedicion, JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_buscarMiembroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiembrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiembrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiembrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiembrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiembrosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoTxt;
    private javax.swing.JButton BorrarBtn1;
    private javax.swing.JButton BorrarMiembrobutton;
    private javax.swing.JButton Miembros;
    private javax.swing.JTable MiembrosTable;
    private javax.swing.JTextField Nacimientotxt;
    private javax.swing.JTextField Nacionalidadtxt;
    private javax.swing.JTextField Nombretxt;
    private javax.swing.JTextField SexoTxt;
    private javax.swing.JLabel accidenteIdLabel;
    private javax.swing.JLabel altitudLabel;
    private javax.swing.JButton buscarMiembro;
    private javax.swing.JLabel cuposLabel;
    private javax.swing.JLabel expedicionesProcesoLabel;
    private javax.swing.JTextField fallecidoTxt;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lidertxt;
    private javax.swing.JLabel mortalidadLabel;
    private javax.swing.JLabel motivoLabel;
    private javax.swing.JButton nuevaExpedicionBtn1;
    private javax.swing.JButton nuevoMiembro;
    private javax.swing.JLabel picoIdLabel;
    private javax.swing.JLabel resultadoLabel;
    private javax.swing.JTextField staftxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
